[build]
  base = "packages/frontend"
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://your-backend-url.railway.app"
  NEXT_PUBLIC_CONTRACT_ID = "0.0.6514484"
  NEXT_PUBLIC_HEDERA_NETWORK = "testnet"
